name: Build and deploy .NET Core application to Azure
on:
  push:
    branches:
    - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: BaruchsTreks
  CONFIGURATION: Release
  DOTNET_VERSION: 8.0.x
  WORKING_DIRECTORY: BaruchsTreks

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

    - name: Build application
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Run tests
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build --verbosity normal

    - name: Publish application
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output ./published

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.BaruchsTreks_2C4B }}
        package: ./published